version: '3.8'

services:
  linktofur-server:
    image: eclipse-temurin:21-jre-alpine
    container_name: linktofur-server
    ports:
      - "127.0.0.1:2778:2778"
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
      - ./main.jar:/app/main.jar
      - ./data:/app/data
    working_dir: /app
    command: ["java", "-jar", "main.jar"]
    restart: unless-stopped
